DROP TABLE IF EXISTS `ACTEUR`;
CREATE TABLE ACTEUR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50)
);
commit;

DROP TABLE IF EXISTS `FILM`;
CREATE TABLE FILM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITRE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CONSTRAINT UC_FILM_TITRE UNIQUE (TITRE)
);
commit;


DROP TABLE IF EXISTS `FILM_ACTEUR`;
CREATE TABLE FILM_ACTEUR (
    film_id BIGINT,
    acteur_id BIGINT,
    PRIMARY KEY (film_id, acteur_id),
    FOREIGN KEY (film_id) REFERENCES FILM(ID),
    FOREIGN KEY (acteur_id) REFERENCES ACTEUR(ID)
);
commit;